package com.duckrace;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

class DuckRacer {
    private int id;
    private String name;
    private final List<Reward> rewards = new ArrayList<>();


//fields
//constructor
    public DuckRacer(int id, String name){
        this.id = id;
        setName(name);
    }
//action or business method
    public void win(Reward reward){
        rewards.add(reward);
    }

//helper method
//accessor method get/set/toString

    public int getId() {
        return id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    //a derived property, it will calculate #wins from the rewards collection
    public int getWins() {
        return rewards.size();
    }
    public List<Reward> getRewards() {
        return Collections.unmodifiableList(rewards);
    }
    //generated by java
    /*@Override
    public String toString() {
        return "DuckRacer{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", rewards=" + rewards +
                '}';
    }
    */
    //self generated
    @Override
    public String toString(){
        return String.format("%s: id=%s, name=%s, wins=%s, rewards=%s",
                getClass().getSimpleName(), getId(), getName(), getWins(), getRewards());
    }
}